server:
  port: 8000

spring:
  cloud:
    gateway:
      default-filters: # ?? ?? ??
        - name: "CustomGlobalFilter" # ??? ?? ??? ?? ??
          args:
            logging: true # ??? ?? ?? ??? ??? ???? args ??

      globalcors: # ??? CORS ??
        cors-configurations:
          '[/**]': # ?? ??? ?? CORS ??
           allowedOrigins: "*" # ?? origin?? ?? ??
           allowedMethods: # ??? HTTP ???
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
           allowedHeaders: # ??? HTTP ???
            - "*"
           allowCredentials: true # ?? ?? ??

      routes: # ??? ??
        - id: auth-service # ??? ???
          uri: "http://localhost:9000" # ??? ??? ?? ???? URI
          predicates: # ???? ??? ??
            - Path=/api/v1/auth/** # ?? ??, /api/v1/auth/** ??? ??? ?? ? ???? ??
        - id: ceo-service
          uri: "http://localhost:9001"
          predicates:
            - Path=/api/v1/owner/**
          filters: # ? ???? ??? ??? ??
            - name: "TokenFilter" # ??? ??? ??
              args:
                logging: false
        - id: store-service
          uri: "http://localhost:9003"
          predicates:
            - Path=/api/v1/store/**
        - id: menu-service
          uri: "http://localhost:9002"
          predicates:
            - Path=/api/v1/menu/**

jwt:
  secret: askjfnlsdkflkasdfkjdnfpsd1087734idjfnmapSdf123asdasd
