server:
  port: 8000

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - name: "CustomGlobalFilter"
          args:
            logging: true
        - name: "CacheFilter"
          args:
            logging: true

      globalcors:
        cors-configurations:
          '[/**]': #
           allowedOrigins: "*"
           allowedMethods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
           allowedHeaders: "*"

      routes:
        - id: auth-service
          uri: "lb://AUTH-SERVICE"
          predicates:
            - Path=/api/v1/auth/**
        - id: ceo-service
          uri: "lb://CEO-SERVICE"
          predicates:
            - Path=/api/v1/owner/**
          filters:
            - name: "TokenFilter"
              args:
                logging: false
        - id: store-service
          uri: "lb://STORE-SERVICE"
          predicates:
            - Path=/api/v1/store/**
        - id: menu-service
          uri: "lb://MENU-SERVICE"
          predicates:
            - Path=/api/v1/menu/**
        - id: customer-service
          uri: "lb://CUSTOMER-SERVICE"
          predicates:
            - Path=/api/v1/customer/**
        - id: pay-service
          uri: "lb://PAY-SERVICE"
          predicates:
            - Path=/api/v1/pay/**

# actuator
management:
  endpoints:
    web:
      exposure:
        include: health,beans,refresh,info

# eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}

  server:
    enable-self-preservation: false